name: Expo publish on push to main
on:
  push:
    branches:
      - main
jobs:
  publish-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # with:
      #   node-version: 14.x
      - uses: expo/expo-github-action@5.1.1
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
      - run: expo publish
